let
    Source = Excel.Workbook(File.Contents("C:\Users\benja\OneDrive\Onedrive\Productivity\Master Date Table.xlsx"), null, true),
    #"Date Table Text_Sheet" = Source{[Item="Date Table Text",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(#"Date Table Text_Sheet", [PromoteAllScalars=true]),
    #"Filtered Rows" = Table.SelectRows(#"Promoted Headers", each [Date] >= #date(2020, 1, 1) and [Date] <= #date(2030, 1, 1)),
    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows",{{"Date", type date}, {"excel date number", Int64.Type}, {"Calendar Year (4 dig)", Int64.Type}, {"Calendar Year (2 dig)", Int64.Type}, {"Month number", Int64.Type}, {"Month Name Short", type text}, {"Month Name Full", type text}, {"Day of month", Int64.Type}, {"Weekday Number", Int64.Type}, {"Weekday Short", type text}, {"Weekday Long", type text}, {"Calendar Quarter", type text}, {"Week Number of the Quarter", Int64.Type}, {"Quarter ID based on month", type text}, {"ISO Week Number", Int64.Type}, {"Week Number (Sunday)", Int64.Type}, {"Epic Quarter", type text}, {"Epic Year 4 Digits", Int64.Type}, {"Epic Year 2 Digits", Int64.Type}, {"Number of weeks in Epic Year", Int64.Type}, {"Number of days in Epic Year", Int64.Type}, {"Fortnight Number", Int64.Type}, {"Fortnight ID", type text}, {"Epic Quarter ID", type text}, {"Week ID", type text}, {"Fiscal Year first 2 digit", Int64.Type}, {"Fiscal Year last 2 digit", Int64.Type}, {"Fiscal Year", type text}, {"Fiscal Quarter", type text}, {"Fiscal Quarter ID", type text}})
in
    #"Changed Type"
